let
    Source = Csv.Document(File.Contents("C:\Users\willthom\Microsoft\Gartner Data and Analytics Summit - Bake-off\WEO_History.txt"),[Delimiter="	", Columns=57, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type text}, {"Column26", type text}, {"Column27", type text}, {"Column28", type text}, {"Column29", type text}, {"Column30", type text}, {"Column31", type text}, {"Column32", type text}, {"Column33", type text}, {"Column34", type text}, {"Column35", type text}, {"Column36", type text}, {"Column37", type text}, {"Column38", type text}, {"Column39", type text}, {"Column40", type text}, {"Column41", type text}, {"Column42", type text}, {"Column43", type text}, {"Column44", type number}, {"Column45", type number}, {"Column46", type number}, {"Column47", type number}, {"Column48", type number}, {"Column49", type number}, {"Column50", type number}, {"Column51", type number}, {"Column52", type number}, {"Column53", type number}, {"Column54", type number}, {"Column55", type number}, {"Column56", type number}, {"Column57", type text}}),
    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"WEO Country Code", Int64.Type}, {"ISO", type text}, {"WEO Subject Code", type text}, {"Country", type text}, {"Subject Descriptor", type text}, {"Subject Notes", type text}, {"Units", type text}, {"Scale", type text}, {"Country/Series-specific Notes", type text}, {"1980", type text}, {"1981", type text}, {"1982", type text}, {"1983", type text}, {"1984", type text}, {"1985", type text}, {"1986", type text}, {"1987", type text}, {"1988", type text}, {"1989", type text}, {"1990", type text}, {"1991", type text}, {"1992", type text}, {"1993", type text}, {"1994", type text}, {"1995", type text}, {"1996", type text}, {"1997", type text}, {"1998", type text}, {"1999", type text}, {"2000", type text}, {"2001", type text}, {"2002", type text}, {"2003", type text}, {"2004", type text}, {"2005", type text}, {"2006", type text}, {"2007", type text}, {"2008", type text}, {"2009", type text}, {"2010", type text}, {"2011", type text}, {"2012", type text}, {"2013", type text}, {"2014", type number}, {"2015", type number}, {"2016", type number}, {"2017", type number}, {"2018", type number}, {"2019", type number}, {"2020", type number}, {"2021", type number}, {"2022", type number}, {"2023", type number}, {"2024", type number}, {"2025", type number}, {"2026", type number}, {"Estimates Start After", Int64.Type}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"WEO Country Code", "Subject Notes", "Country/Series-specific Notes", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2022", "2023", "2024", "2025", "2026", "Estimates Start After"}),
    #"Replaced Errors" = Table.ReplaceErrorValues(#"Removed Columns", {{"2019", null}, {"2020", null}, {"2021", null}}),
    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Replaced Errors", {"ISO", "WEO Subject Code", "Country", "Subject Descriptor", "Units", "Scale"}, "Attribute", "Value"),
    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Year"}}),
    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Subject Descriptor] = "Gross domestic product, constant prices")),
    #"Pivoted Column" = Table.Pivot(#"Filtered Rows", List.Distinct(#"Filtered Rows"[Units]), "Units", "Value", List.Sum),
    #"Grouped Rows" = Table.Group(#"Pivoted Column", {"ISO", "Country", "Year"}, {{"GDP (bn)", each List.Sum([National currency]), type nullable number}, {"% change", each List.Sum([Percent change]), type nullable number}}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Grouped Rows",{{"Year", Int64.Type}})
in
    #"Changed Type2"