let
    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv"),[Delimiter=",", Columns=46, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CountryName", type text}, {"CountryCode", type text}, {"RegionName", type text}, {"RegionCode", type text}, {"Jurisdiction", type text}, {"Date", Int64.Type}, {"C1_School closing", type text}, {"C1_Flag", type text}, {"C2_Workplace closing", type text}, {"C2_Flag", type text}, {"C3_Cancel public events", type text}, {"C3_Flag", type text}, {"C4_Restrictions on gatherings", type text}, {"C4_Flag", type text}, {"C5_Close public transport", type text}, {"C5_Flag", type text}, {"C6_Stay at home requirements", type text}, {"C6_Flag", type text}, {"C7_Restrictions on internal movement", type text}, {"C7_Flag", type text}, {"C8_International travel controls", type text}, {"E1_Income support", type text}, {"E1_Flag", type text}, {"E2_Debt/contract relief", type text}, {"E3_Fiscal measures", type text}, {"E4_International support", type text}, {"H1_Public information campaigns", type text}, {"H1_Flag", type text}, {"H2_Testing policy", type text}, {"H3_Contact tracing", type text}, {"H4_Emergency investment in healthcare", type text}, {"H5_Investment in vaccines", type text}, {"H6_Facial Coverings", type text}, {"H6_Flag", type text}, {"H7_Vaccination policy", type text}, {"H7_Flag", type text}, {"H8_Protection of elderly people", type text}, {"H8_Flag", type text}, {"M1_Wildcard", type text}, {"ConfirmedCases", Int64.Type}, {"ConfirmedDeaths", Int64.Type}, {"StringencyIndex", type number}, {"StringencyIndexForDisplay", type number}, {"StringencyLegacyIndex", type number}, {"StringencyLegacyIndexForDisplay", type number}, {"GovernmentResponseIndex", type number}}),
    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Jurisdiction] = "STATE_TOTAL") and ([CountryName] = "United States")),
    #"Inserted Date" = Table.AddColumn(#"Filtered Rows", "CalDate", each Date.From(Text.From([Date], "en-US")), type date)
in
    #"Inserted Date"