let
    Source = Web.BrowserContents("https://simple.wikipedia.org/wiki/List_of_U.S._states_by_population"),
    #"Extracted Table From Html" = Html.Table(Source, {{"Column1", "TABLE.wikitable.sortable > * > TR > :nth-child(1)"}, {"Column2", "TABLE.wikitable.sortable > * > TR > :nth-child(2)"}, {"Column3", "TABLE.wikitable.sortable > * > TR > :nth-child(3)"}, {"Column4", "TABLE.wikitable.sortable > * > TR > :nth-child(4)"}, {"Column5", "TABLE.wikitable.sortable > * > TR > :nth-child(5)"}, {"Column6", "TABLE.wikitable.sortable > * > TR > :nth-child(6)"}, {"Column7", "TABLE.wikitable.sortable > * > TR > :nth-child(7)"}, {"Column8", "TABLE.wikitable.sortable > * > TR > :nth-child(8)"}, {"Column9", "TABLE.wikitable.sortable > * > TR > :nth-child(9)"}, {"Column10", "TABLE.wikitable.sortable > * > TR > :nth-child(10)"}, {"Column11", "TABLE.wikitable.sortable > * > TR > :nth-child(11)"}, {"Column12", "TABLE.wikitable.sortable > * > TR > :nth-child(12)"}}, [RowSelector="TABLE.wikitable.sortable > * > TR"]),
    #"Promoted Headers" = Table.PromoteHeaders(#"Extracted Table From Html", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Rank in states & territories, 2019", type text}, {"Rank in states & territories, 2010", type text}, {"State", type text}, {"Population estimate, July 1, 2019[2]", Int64.Type}, {"Census population, April 1, 2010[3]", type text}, {"Percent change, 2010–2019[note 1]", Percentage.Type}, {"Absolute change, 2010-2019", type text}, {"Total seats in the U.S. House of Representatives, 2013–2023", type text}, {"Estimated population per electoral vote, 2019[note 2]", type text}, {"Estimated population per House seat, 2019", type text}, {"Census population per House seat, 2010", type text}, {"Percent of the total U.S. population, 2018[note 3]", Percentage.Type}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"State", "Population estimate, July 1, 2019[2]"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Removed Other Columns","U.S. ","",Replacer.ReplaceText,{"State"}),
    #"Filtered Rows" = Table.SelectRows(#"Replaced Value1", each ([State] <> "Contiguous United States" and [State] <> "Fifty states + D.C." and [State] <> "The fifty states" and [State] <> "Total (including D.C. and territories)"))
in
    #"Filtered Rows"