SWITCH(
  TRUE,
  ISBLANK('States'[State]),
  "(Blank)",
  'States'[State] IN {"Alaska",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Maine",
    "Marshall Islands",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Missouri",
    "Montana",
    "Nebraska",
    "New Hampshire",
    "New Jersey",
    "New York",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Puerto Rico",
    "Rhode Island",
    "South Dakota",
    "Vermont",
    "Virgin Islands",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming"},
  "Cooler",
  'States'[State] IN {"Alabama",
    "American Samoa",
    "Arizona",
    "Arkansas",
    "California",
    "Florida",
    "Georgia",
    "Guam",
    "Hawaii",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Mississippi",
    "Nevada",
    "New Mexico",
    "North Carolina",
    "South Carolina",
    "Tennessee",
    "Texas",
    "Utah"},
  "Hotter",
  'States'[State]
)