
var daysRecorded =  COUNTROWS(VALUES('OWID COVID data'[date]))
return SUMMARIZECOLUMNS('Days with restrictions'[CountryCode], 
"School closures",                  switch(true(), daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[School closures] = "No measures"              )) <100, "<100 days", daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[School closures] = "No measures"               )) <200, "100-200 days" , daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[School closures] = "No measures"               )) <300, "200-300 days" ,">300 days"),
"Workplace closures",               switch(true(), daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Workplace closures] = "No measures"           )) <100, "<100 days", daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Workplace closures] = "No measures"            )) <200, "100-200 days" , daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Workplace closures] = "No measures"            )) <300, "200-300 days" ,">300 days"),
"Cancelling public events",         switch(true(), daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Cancelling public events] = "No measures"     )) <100, "<100 days", daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Cancelling public events] = "No measures"      )) <200, "100-200 days" , daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Cancelling public events] = "No measures"      )) <300, "200-300 days" ,">300 days"),
"Restrictions on gathering",        switch(true(), daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Restrictions on gathering] = "No measures"    )) <100, "<100 days", daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Restrictions on gathering] = "No measures"     )) <200, "100-200 days" , daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Restrictions on gathering] = "No measures"     )) <300, "200-300 days" ,">300 days"),
"Public transport closures",        switch(true(), daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Public transport closures] = "No measures"    )) <100, "<100 days", daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Public transport closures] = "No measures"     )) <200, "100-200 days" , daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Public transport closures] = "No measures"     )) <300, "200-300 days" ,">300 days"),
"Stay at home requirements",        switch(true(), daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Stay at home requirements] = "No measures"    )) <100, "<100 days", daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Stay at home requirements] = "No measures"     )) <200, "100-200 days" , daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Stay at home requirements] = "No measures"     )) <300, "200-300 days" ,">300 days"),
"Domestic travel restrictions",      switch(true(), daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Internal mov't restrictions] = "No measures"  )) <100, "<100 days", daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Internal mov't restrictions] = "No measures"   )) <200, "100-200 days" , daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Internal mov't restrictions] = "No measures"   )) <300, "200-300 days" ,">300 days"),
"International travel controls",    switch(true(), daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[International travel controls] = "No measures")) <100, "<100 days", daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[International travel controls] = "No measures" )) <200, "100-200 days" , daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[International travel controls] = "No measures" )) <300, "200-300 days" ,">300 days"),
"Face coverings required",          switch(true(), daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Face coverings] = "No measures"               )) <100, "<100 days", daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Face coverings] = "No measures"                )) <200, "100-200 days" , daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Face coverings] = "No measures"                )) <300, "200-300 days" ,">300 days"),
"Vaccinations available",           switch(true(), daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Vaccination policy] = "No availability"       )) <100, "<100 days", daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Vaccination policy] = "No availability"        )) <200, "100-200 days" , daysRecorded - COUNTROWS(FILTER('CGRT Mandates', 'CGRT Mandates'[Vaccination policy] = "No availability"        )) <300, "200-300 days" ,">300 days") 

)