
var numCases = CALCULATE (
    SUM( 'Cases per US State'[Incremental cases] )/7,
    DATESINPERIOD (
        'Dates'[Date],
        min('Dates'[Date] ),
        -7,
        DAY
    ))

var pop = SUM(States[Population])
return DIVIDE(numCases, pop)*1000000